version: '3.8'

services:
  # Frontend React/Vite
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5679:5679"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - isti-network

  # Backend Node.js/Express
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/isti_db
      - JWT_SECRET=isti-secret-key-2024
      - FRONTEND_URL=http://localhost:5679
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - isti-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # PostgreSQL Database
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: isti_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - isti-network

volumes:
  postgres_data:

networks:
  isti-network:
    driver: bridge